services:
  - type: web
    name: usda-land-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_DB_URL
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: PORT
        value: 10000

  - type: web
    name: usda-land-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: usda-land-backend
          property: host

databases:
  - name: mongodb
    databaseName: usda_land_db